# Generated by Django 4.2.5 on 2023-10-07 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mileage',
            name='moto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mileage', to='vehicle.moto'),
        ),
    ]
